<?php
require_once './sessions/session_admin.php';
require_once '../../config/db_connection.php';

// Validate session
if (!isset($_SESSION['userID'])) {
    header("Location: ../../index.php");
    exit;
}

$userID = filter_var($_SESSION['userID'], FILTER_VALIDATE_INT);
if ($userID === false) {
    session_destroy();
    header("Location: ../../index.php");
    exit;
}

try {
    // Fetch user data for filename
    $stmt = $dbConnection->prepare("SELECT firstName FROM users WHERE userID = :userID");
    $stmt->bindParam(':userID', $userID, PDO::PARAM_INT);
    $stmt->execute();
    $user = $stmt->fetch(PDO::FETCH_ASSOC);

    if (!$user) {
        session_destroy();
        header("Location: ../../index.php");
        exit;
    }
    $safeAdminName = htmlspecialchars($user['firstName']);

    // User counts
    $userCounts = [
        'Admin' => 'Administrators',
        'Professor' => 'Teachers',
        'Student' => 'Students',
    ];

    $counts = [];
    foreach ($userCounts as $key => $displayName) {
        $stmt = $dbConnection->prepare("SELECT COUNT(*) FROM users WHERE userType = :userType AND archived = 0");
        $stmt->bindParam(':userType', $key, PDO::PARAM_STR);
        $stmt->execute();
        $counts[$key] = (int)$stmt->fetchColumn();
    }

    // Counts for tracks, sections, subjects
    $stmt = $dbConnection->prepare("SELECT COUNT(*) FROM track_strands WHERE archived = 0");
    $stmt->execute();
    $strandCount = (int)$stmt->fetchColumn();

    $stmt = $dbConnection->prepare("SELECT COUNT(*) FROM sections WHERE archived = 0");
    $stmt->execute();
    $sectionCount = (int)$stmt->fetchColumn();

    $stmt = $dbConnection->prepare("SELECT COUNT(*) FROM subjects WHERE archived = 0");
    $stmt->execute();
    $subjectCount = (int)$stmt->fetchColumn();

    // Enrollment records with student names
    $stmt = $dbConnection->prepare("
        SELECT ss.userID, ss.enrollmentDate, u.firstName, u.lastName
        FROM student_section ss
        JOIN users u ON ss.userID = u.userID
        WHERE ss.status = 'Enrolled' AND ss.archived = 0
        ORDER BY ss.enrollmentDate
    ");
    $stmt->execute();
    $enrollmentData = $stmt->fetchAll(PDO::FETCH_ASSOC);

    // Set headers for CSV download
    $filename = "Learnify_Report_{$safeAdminName}_" . date('Ymd_His') . ".csv";
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $filename . '"');

    // Create a file pointer connected to the output stream
    $output = fopen('php://output', 'w');

    // Write CSV content
    fputcsv($output, ['Learnify Dashboard Report']);
    fputcsv($output, ['Generated by', $safeAdminName]);
    fputcsv($output, ['Generated on', date('Y-m-d H:i:s')]);
    fputcsv($output, []); // Empty row for spacing

    // User Counts Section
    fputcsv($output, ['User Distribution']);
    fputcsv($output, ['User Type', 'Count']);
    foreach ($userCounts as $key => $displayName) {
        if ($counts[$key] > 0) {
            fputcsv($output, [$displayName, $counts[$key]]);
        }
    }
    fputcsv($output, []); // Empty row for spacing

    // Other Counts Section
    fputcsv($output, ['Other Metrics']);
    fputcsv($output, ['Metric', 'Count']);
    fputcsv($output, ['Tracks and Strands', $strandCount]);
    fputcsv($output, ['Sections', $sectionCount]);
    fputcsv($output, ['Subjects', $subjectCount]);
    fputcsv($output, []); // Empty row for spacing

    // Enrollment Records Section
    fputcsv($output, ['Enrollment Records']);
    fputcsv($output, ['User ID', 'Student Name', 'Enrollment Date']);
    foreach ($enrollmentData as $data) {
        $date = new DateTime($data['enrollmentDate']);
        $formattedDate = $date->format('F j, Y \a\t g:ia');
        $studentName = htmlspecialchars($data['firstName'] . ' ' . ($data['lastName'] ?? ''));
        fputcsv($output, [$data['userID'], $studentName, $formattedDate]);
    }

    // Close the output stream
    fclose($output);
    exit;

} catch (PDOException $e) {
    error_log("Database Error: " . $e->getMessage() . " in " . $e->getFile() . " on line " . $e->getLine());
    $_SESSION['error_message'] = "An error occurred while generating the report: " . htmlspecialchars($e->getMessage());
    header("Location: ./adminDash.php");
    exit;
}
?>